### ISSUE TITLE
02 -  View Detail

### ISSUE THREAD

**Issue by Reylyer** [Reylyer/pbp-perpus#3]
Include

- show data detail buku 
   - kategori
   - judul
   - nama pengarang
   - penerbit
   - tahun
   - ISBN
- stok tersedia yang dipinjam
- kolom untuk user komentar
  - rating
  - komentar

**Comment by Reylyer** [comment]
add detail tugas untuk view detail (SRS 02 / Kelompok 1)

**Comment by ZZIDZZ** [comment]
instruction unclear, got my hand stuck on my pants

**Comment by Reylyer** [comment]
done (not including fitur untuk rate, ada untuk srs 04) selesai di commit [9a6c9e6](https://github.com/Reylyer/pbp-perpus/commit/9a6c9e6e3069a43d0a9541e829be07cc897b0fc5)
