### ISSUE TITLE
04 - Rating dan Komentar

### ISSUE THREAD

**Issue by Reylyer** [Reylyer/pbp-perpus#8]

**Comment by Reylyer** [comment]
Komentar udah tinggal rating (agak bingung dengan satu kali saja setiap buku) meminta diskusi

**Comment by naufaldzakiim** [comment]
rating sudah aman, tiap user hanya bisa kirim sekali untuk 1 buku.
question: apakah perlu user dapat mengubah rating dari buku yg sudah pernah diberi rating?

**Comment by naufaldzakiim** [comment]
done di commit [345e8e](https://github.com/Reylyer/pbp-perpus/commit/345e8eaf7c629bc2193b83d211dd28ad9c1239ab)
